### ISSUE TITLE
[Bug] Issue in Webpack Compilation

### ISSUE THREAD

**Issue by csuf-mm** [awslabs/service-workbench-on-aws#1243]
When deploying Service Workbench for the first time, the Webpack compilation fails due to an unexpected token in a supporting file.

Here is a dump of the error:

```
Webpack compilation failed:

in /home/ec2-user/environment/service-workbench-on-aws/node_modules/.pnpm/@smithy/service-error-classification@2.0.6/node_modules/@smithy/service-error-classification/dist-es/index.js 6:21
  Module parse failed: Unexpected token (6:21)
  You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
  | export const isThrottlingError = (error) => error.$metadata.httpStatusCode === 429 ||
  |     THROTTLING_ERROR_CODES.includes(error.name) ||
  >     error.$retryable?.throttling == true;
  | export const isTransientError = (error) => TRANSIENT_ERROR_CODES.includes(error.name) ||
  |     NODEJS_TIMEOUT_ERROR_CODES.includes(error?.code || "") ||
```

I did not expect to have to edit working files but removing the question marks resolved the step.

Version installed: 6.2.0
Solution was cloned locally

Fix?
After removing question marks on 4:60, 6:21, 8:46, and 11:24 in this file: /service-workbench-on-aws/node_modules/.pnpm/@smithy/service-error-classification@2.0.6/node_modules/@smithy/service-error-classification/dist-es/index.js, the step completed successfully. 

Did not send a pull request.

**Comment by maghirardelli** [comment]
Hi @csuf-mm it looks like the problem is coming from your node modules, not SWB code. We have confirmed fresh installs work with v6.2.0. Please delete your node modules folder and reinstall the dependencies to resolve this issue!

**Comment by csuf-mm** [comment]
Ok, thank you!
